version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cognito-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1889y6al4zbcs"
s3_prefix = "cognito-lambda"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
